name: qsmartapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_database:
  shared_preferences: ^0.5.4+1
  fluttertoast: ^3.1.3
  firebase_auth:
  provider:
  flutter_swiper: ^1.1.6
  screen: ^0.0.5
  carousel_pro:
  flutter_screenutil: ^0.6.0
  flutter_html:
  google_fonts: ^0.3.2
  timeago: ^2.0.24
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - images/
  - images/gallery/